# services.yaml

config:
  timeout: 4000

vars:
  host: http://dummy.restapiexample.com/api/v1

services:

  employee:
    url: ${host}/employee/24863
    successCode: 200
    timeout: 2000
    method: GET
    
  employees:
    url: ${host}/employees00
  
  employees-2:
    url: ${host}/employees

  employees-3:
    url: ${host}/employees

  employees-4:
    url: ${host}/employees66

  employees-5:
    url: ${host}/employees